# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Windows-Self

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: |
     BoatControl.Shared.Bluetooth/BoatControl.Shared.Bluetooth.csproj
     BoatControl.Shared/BoatControl.Shared.csproj
    vstsFeed: 'c2368f44-fb5e-4a60-a795-ddd0e59d8a55'
#- task: DotNetCoreCLI@2
#  displayName: Build
#  inputs:
#    command: build
#    projects: |
#     BoatControl.Shared.Bluetooth/BoatControl.Shared.Bluetooth.csproj
#     BoatControl.Shared/BoatControl.Shared.csproj

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: pack
    packagesToPack: 'BoatControl.Shared.Bluetooth/BoatControl.Shared.Bluetooth.csproj;BoatControl.Shared/BoatControl.Shared.csproj'
    versioningScheme: byPrereleaseNumber
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'c2368f44-fb5e-4a60-a795-ddd0e59d8a55'
    allowPackageConflicts: true

